dist: trusty
language: java
jdk:
- openjdk11

addons:
  sonarcloud:
    organization: gulixciurli
    token: b5f91274f32b9f439c48fd6a21fe7c93dfb30f9b

     
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=myorg_myrepo

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn compile sonar:sonar  -Dsonar.projectKey=gulixciurli_bookkeeper -Ppit  -Dmaven.javadoc.skip=true

  # - mvn clean -DskipTests
